"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
format = """
[](fg:#222524 bg:bright-cyan)$username$hostname[ ](fg:bright-cyan bg:bright-blue)\
$directory[ ](fg:bright-blue bg:bright-purple)\
$git_branch[ ](fg:bright-purple)\
$git_state$git_status$git_metrics
$character\
"""

right_format = """
$cmd_duration\
$time
"""

# === who/where ===
[username]
show_always = true
format = "[ $user]($style)"
style_user = "black bg:bright-cyan"

[hostname]
ssh_only = false
format = "[󰍹 $hostname]($style)"
style = "black bg:bright-cyan"

# === path ===
[directory]
home_symbol = "~"
truncation_length = 0
truncate_to_repo = false
style = "black bg:bright-blue"
format = "[ $path ]($style)[$read_only]($read_only_style)"

# === git branch ===
[git_branch]
format = "([$symbol$branch ]($style))"
style = "black bg:bright-purple"

# === git status (差分・↑↓) ===
[git_status]
format = "([ $all_status$ahead_behind]($style) )"
style = "yellow"
staged = "[+$count](cyan)"
modified = "[~$count](yellow)"
untracked = "[?$count](red)"
deleted = "[-$count](red)"
conflicted = "[✖$count](red)"
stashed = "[$count](blue)"
ahead = "[⇡$count](bold cyan)"
behind = "[⇣$count](bold red)"
diverged = "[⇡$ahead_count⇣$behind_count](bold purple)"
up_to_date = ""

[git_metrics]
disabled = false
only_nonzero_diffs = true
ignore_submodules = true
format = "([ ](yellow)([+$added]($added_style))/([-$deleted]($deleted_style)) )"

# === prompt symbol ===
[character]
success_symbol = "[󰣧](white) "
error_symbol   = "[󰣧](red) "

# === right settings ===

[cmd_duration]
min_time = 1
show_milliseconds = true
style = 'black bg:bright-yellow'
format = "[](bright-yellow)[ 󰄉 $duration ]($style)"

[time]
disabled = false
utc_time_offset= "9"
time_format = "%T" # https://docs.rs/chrono/0.4.7/chrono/format/strftime/index.html
style = "black bg:bright-green"
format = '[  $time ]($style)[](bright-green)'
